# Generated by Django 2.1.2 on 2018-10-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('capacidade', models.IntegerField()),
                ('status', models.CharField(choices=[('disponivel', 'DISPONIVEL'), ('indisponivel', 'INDISPONIVEL')], max_length=20)),
                ('obs', models.CharField(max_length=200)),
            ],
        ),
    ]
