# Generated by Django 2.1.2 on 2018-10-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181017_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamentos',
            old_name='título',
            new_name='titulo',
        ),
    ]
