# Generated by Django 2.1.2 on 2018-10-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181017_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='termino',
            field=models.DateTimeField(),
        ),
    ]
