# Generated by Django 2.1.2 on 2018-10-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181017_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='inicio',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='termino',
            field=models.DateTimeField(unique=True),
        ),
    ]
