# Generated by Django 2.1.2 on 2018-10-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_salas_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentos',
            name='id',
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Salas'),
        ),
    ]
