# Generated by Django 2.1.2 on 2018-10-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181018_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Salas'),
        ),
    ]
