# Generated by Django 2.1 on 2018-10-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181018_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentos',
            name='data',
        ),
    ]
