# Generated by Django 2.1 on 2018-10-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181019_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='termino',
            field=models.DateTimeField(),
        ),
    ]
