# Generated by Django 2.1 on 2018-10-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20181019_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Salas'),
        ),
    ]
